- name: play level  variable 
  hosts: localhost
  connection: local #ansible_connection=local
  vars:
   COURSE: Ansible
   DURATION: 10HRS
   Trainer: Kranthikumar
  tasks:
  - name: print course details
    ansible.builtin.debug:
      msg: "Course Name is {{ COURSE }} and Duration is {{ DURATION }} and Trainer is {{ Trainer }}"
