- name: play level variable
  hosts: frontend
  connection: local 
  vars:
    COURSE: DevOps with AWS
    DURATION: 10HRS
    Trainer: Kranthi kumar
  tasks:
    - name: print the course info
      vars:
        COURSE: Ansible
        DURATION: 5HRS
      ansible.builtin.debug:
        msg: "Course name is: {{ COURSE }} and Duration is: {{ DURATION }} and Trainer is: {{ Trainer }}"