- name: variables from prompt
  hosts: local
  connection: local # Ansible is connecting to localhost
  vars_prompt:
    - name: username
      prompt: "what's your name?"
      private: false
      -name: password
      prompt: "Enter your password"
      private: true
  tasks:
  - name: print credentials
    ansible.builtin.debug:
      msg: "Hello, username is: {{ username }}, password is: {{ password }}"
