- name: vars preference
  hosts: local
  connection: local
  vars:
   NAME: from play level
  vars_files:
  - course.yaml
  vars_prompt:
   name: NAME
   prompt: what is your name?
   private: false
  tasks:
  - name: testing variables preference
    vars:
    NAME: task from level
    ansible.builtin.debug:
      msg: "Hello, {{ NAME }}. Course Name is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ Trainer }}"
        