- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: print names
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
    loop:
      - { name: "git", state: "present" }
      - { name: "nginx", state: "absent" }
      - { name: "mysql", state: "absent" }
      - { name: "zip", state: "latest" }
      