- name: user creation
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: create user1
    ansible.builtin.user:
      name: user1
      state: present
    register: user1_creation
    ignore_errors: true